-- Run this migration in the Supabase SQL Editor.
-- Anonymous users can read posts/stories and retrieve public photos; mutations
-- and account data require authentication and owner-scoped RLS policies.

CREATE TABLE IF NOT EXISTS public.posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  content text NOT NULL DEFAULT '',
  image_url text,
  media_url text,
  video_url text,
  media_type text NOT NULL DEFAULT 'image',
  created_at timestamptz NOT NULL DEFAULT now(),
  likes integer NOT NULL DEFAULT 0
);
INSERT INTO storage.buckets (id, name, public)
VALUES ('avatars', 'avatars', true), ('photos', 'photos', true), ('post-images', 'post-images', true)
ON CONFLICT (id) DO UPDATE SET public = true;

ALTER TABLE public.posts
  ADD COLUMN IF NOT EXISTS user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS content text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS image_url text,
  ADD COLUMN IF NOT EXISTS media_url text,
  ADD COLUMN IF NOT EXISTS video_url text,
  ADD COLUMN IF NOT EXISTS media_type text NOT NULL DEFAULT 'image',
  ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now(),
  ADD COLUMN IF NOT EXISTS likes integer NOT NULL DEFAULT 0,
  ALTER COLUMN image_url DROP NOT NULL;

ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow all" ON public.posts;
DROP POLICY IF EXISTS "anon can select posts" ON public.posts;
DROP POLICY IF EXISTS "anon can insert posts" ON public.posts;
DROP POLICY IF EXISTS "posts readable by everyone" ON public.posts;
DROP POLICY IF EXISTS "posts_select_all" ON public.posts;
DROP POLICY IF EXISTS "posts_insert_own" ON public.posts;
DROP POLICY IF EXISTS "posts_delete_own" ON public.posts;
DROP POLICY IF EXISTS "public can read posts" ON public.posts;
DROP POLICY IF EXISTS "public can create posts" ON public.posts;
DROP POLICY IF EXISTS "public can update post likes" ON public.posts;
DROP POLICY IF EXISTS "authenticated users create own posts" ON public.posts;
DROP POLICY IF EXISTS "allow all" ON public.likes;
DROP POLICY IF EXISTS "authenticated users manage own posts" ON public.posts;
DROP POLICY IF EXISTS "authenticated users delete own posts" ON public.posts;

CREATE POLICY "public can read posts"
  ON public.posts FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "authenticated users create own posts"
  ON public.posts FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY "authenticated users manage own posts"
  ON public.posts FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "authenticated users delete own posts"
  ON public.posts FOR DELETE TO authenticated USING (auth.uid() = user_id);
GRANT SELECT ON public.posts TO anon, authenticated;
GRANT INSERT, UPDATE ON public.posts TO authenticated;
REVOKE UPDATE ON public.posts FROM anon;
CREATE TABLE IF NOT EXISTS public.likes (
  post_id bigint NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (post_id, user_id)
);
ALTER TABLE public.likes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow all" ON public.likes;
DROP POLICY IF EXISTS "users read own likes" ON public.likes;
DROP POLICY IF EXISTS "users manage own likes" ON public.likes;
DROP POLICY IF EXISTS "users create own likes" ON public.likes;
DROP POLICY IF EXISTS "users remove own likes" ON public.likes;
DROP POLICY IF EXISTS "likes_select_all" ON public.likes;
DROP POLICY IF EXISTS "likes_insert_own" ON public.likes;
DROP POLICY IF EXISTS "likes_delete_own" ON public.likes;
CREATE POLICY "users read own likes"
  ON public.likes FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "users create own likes"
  ON public.likes FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "users remove own likes"
  ON public.likes FOR DELETE TO authenticated USING (auth.uid() = user_id);
GRANT SELECT, INSERT, DELETE ON public.likes TO authenticated;

CREATE OR REPLACE FUNCTION public.sync_post_like_count()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  target_post_id bigint;
BEGIN
  target_post_id := CASE WHEN TG_OP = 'INSERT' THEN NEW.post_id ELSE OLD.post_id END;
  UPDATE public.posts
  SET likes = GREATEST(0, likes + CASE WHEN TG_OP = 'INSERT' THEN 1 ELSE -1 END)
  WHERE id = target_post_id;
  RETURN NULL;
END;
$$;
UPDATE public.posts AS post
SET likes = (SELECT count(*)::integer FROM public.likes AS liked WHERE liked.post_id = post.id);
DROP TRIGGER IF EXISTS sync_post_like_count ON public.likes;
CREATE TRIGGER sync_post_like_count
  AFTER INSERT OR DELETE ON public.likes
  FOR EACH ROW EXECUTE FUNCTION public.sync_post_like_count();

CREATE TABLE IF NOT EXISTS public.accounts (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  balance numeric(12, 2) NOT NULL DEFAULT 0 CHECK (balance >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.accounts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow all" ON public.accounts;
DROP POLICY IF EXISTS "account owner reads account" ON public.accounts;
CREATE POLICY "account owner reads account"
  ON public.accounts FOR SELECT TO authenticated USING (auth.uid() = id);
GRANT SELECT ON public.accounts TO authenticated;

CREATE TABLE IF NOT EXISTS public.stories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  name text NOT NULL DEFAULT '',
  image_url text NOT NULL DEFAULT '',
  media_url text,
  video_url text,
  media_type text NOT NULL DEFAULT 'image',
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.stories ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow all" ON public.stories;
DROP POLICY IF EXISTS "stories readable by everyone" ON public.stories;
DROP POLICY IF EXISTS "public can create stories" ON public.stories;
CREATE POLICY "stories readable by everyone"
  ON public.stories FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "public can create stories"
  ON public.stories FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid());
GRANT SELECT ON public.stories TO anon, authenticated;
GRANT INSERT ON public.stories TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.stories_id_seq TO authenticated;

CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name text NOT NULL DEFAULT '',
  username text,
  bio text NOT NULL DEFAULT '',
  avatar_url text NOT NULL DEFAULT '',
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS full_name text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS username text,
  ADD COLUMN IF NOT EXISTS bio text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS avatar_url text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow all" ON public.profiles;
DROP POLICY IF EXISTS "public profile readable" ON public.profiles;
DROP POLICY IF EXISTS "public profile editable" ON public.profiles;
DROP POLICY IF EXISTS "profiles_select_all" ON public.profiles;
DROP POLICY IF EXISTS "profiles_insert_own" ON public.profiles;
DROP POLICY IF EXISTS "profiles_update_own" ON public.profiles;
DROP POLICY IF EXISTS "users create own profile" ON public.profiles;
DROP POLICY IF EXISTS "users manage own profile" ON public.profiles;
CREATE POLICY "public profile readable"
  ON public.profiles FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "users create own profile"
  ON public.profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);
CREATE POLICY "users manage own profile"
  ON public.profiles FOR UPDATE TO authenticated
  USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
GRANT SELECT ON public.profiles TO anon, authenticated;
GRANT INSERT, UPDATE ON public.profiles TO authenticated;
GRANT INSERT ON public.profiles TO service_role;

INSERT INTO public.profiles (id, username, full_name, avatar_url)
SELECT
  users.id,
  split_part(COALESCE(users.email, ''), '@', 1),
  COALESCE(
    NULLIF(users.raw_user_meta_data ->> 'full_name', ''),
    split_part(COALESCE(users.email, ''), '@', 1)
  ),
  'https://i.pravatar.cc/150?u=' || COALESCE(users.email, users.id::text)
FROM auth.users AS users
ON CONFLICT (id) DO NOTHING;

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  new_username text;
BEGIN
  new_username := split_part(COALESCE(NEW.email, ''), '@', 1);
  INSERT INTO public.profiles (id, username, full_name, avatar_url)
  VALUES (
    NEW.id,
    new_username,
    COALESCE(NULLIF(NEW.raw_user_meta_data ->> 'full_name', ''), new_username),
    COALESCE(NEW.raw_user_meta_data ->> 'avatar_url', '')
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

ALTER TABLE public.likes
  DROP CONSTRAINT IF EXISTS likes_user_id_fkey;
ALTER TABLE public.likes
  ADD CONSTRAINT likes_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;
ALTER TABLE public.stories
  DROP CONSTRAINT IF EXISTS stories_user_id_fkey;
ALTER TABLE public.stories
  ADD CONSTRAINT stories_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE SET NULL;
ALTER TABLE public.posts
  DROP CONSTRAINT IF EXISTS posts_user_id_fkey;
ALTER TABLE public.posts
  ADD CONSTRAINT posts_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE SET NULL;

DROP POLICY IF EXISTS "post images are public" ON storage.objects;
DROP POLICY IF EXISTS "anon can upload post images" ON storage.objects;
DROP POLICY IF EXISTS "photos images are public" ON storage.objects;
DROP POLICY IF EXISTS "anon can upload photos" ON storage.objects;
CREATE POLICY "photos images are public"
  ON storage.objects FOR SELECT TO anon, authenticated USING (bucket_id = 'photos');
CREATE POLICY "authenticated users can upload photos"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'photos');

DROP POLICY IF EXISTS "post images are public" ON storage.objects;
DROP POLICY IF EXISTS "authenticated users can upload post images" ON storage.objects;
CREATE POLICY "post images are public"
  ON storage.objects FOR SELECT TO anon, authenticated USING (bucket_id = 'post-images');
CREATE POLICY "authenticated users can upload post images"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'post-images');

DROP POLICY IF EXISTS "avatar images are public" ON storage.objects;
DROP POLICY IF EXISTS "anon can upload avatars" ON storage.objects;
DROP POLICY IF EXISTS "Avatar public read" ON storage.objects;
DROP POLICY IF EXISTS "Avatar user upload" ON storage.objects;
DROP POLICY IF EXISTS "Avatar user update" ON storage.objects;
DROP POLICY IF EXISTS "Avatar user delete" ON storage.objects;
DROP POLICY IF EXISTS "authenticated users can upload avatars" ON storage.objects;
DROP POLICY IF EXISTS "avatars owner upload" ON storage.objects;
DROP POLICY IF EXISTS "avatars owner update" ON storage.objects;
DROP POLICY IF EXISTS "avatars owner delete" ON storage.objects;
CREATE POLICY "avatar images are public"
  ON storage.objects FOR SELECT TO anon, authenticated USING (bucket_id = 'avatars');
CREATE POLICY "avatars owner upload"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'avatars'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );
CREATE POLICY "avatars owner update"
  ON storage.objects FOR UPDATE TO authenticated
  USING (
    bucket_id = 'avatars'
    AND (storage.foldername(name))[1] = auth.uid()::text
  )
  WITH CHECK (
    bucket_id = 'avatars'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );
CREATE POLICY "avatars owner delete"
  ON storage.objects FOR DELETE TO authenticated
  USING (
    bucket_id = 'avatars'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

NOTIFY pgrst, 'reload schema';
