-- Run once in the Supabase SQL Editor to enable referral rewards, like rewards,
-- durable account balances, and atomic withdrawal requests.

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS referral_code text,
  ADD COLUMN IF NOT EXISTS referred_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL;

UPDATE public.profiles
SET referral_code = upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 10))
WHERE referral_code IS NULL OR referral_code = '';

CREATE UNIQUE INDEX IF NOT EXISTS profiles_referral_code_unique
  ON public.profiles (referral_code);
CREATE INDEX IF NOT EXISTS profiles_referred_by_idx
  ON public.profiles (referred_by);
REVOKE UPDATE ON public.profiles FROM authenticated;
GRANT UPDATE (full_name, username, bio, avatar_url) ON public.profiles TO authenticated;

ALTER TABLE public.accounts
  ADD COLUMN IF NOT EXISTS blue_points bigint NOT NULL DEFAULT 0 CHECK (blue_points >= 0);
ALTER TABLE public.accounts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "account owner reads account" ON public.accounts;
CREATE POLICY "account owner reads account"
  ON public.accounts FOR SELECT TO authenticated USING (auth.uid() = id);
GRANT SELECT ON public.accounts TO authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.accounts FROM anon, authenticated;

INSERT INTO public.accounts (id, balance, blue_points)
SELECT id, 0, 0 FROM public.profiles
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.reward_ledger (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_key text NOT NULL UNIQUE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  blue_points_delta bigint NOT NULL,
  amount_delta numeric(12, 2) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.reward_ledger ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "users read own reward ledger" ON public.reward_ledger;
CREATE POLICY "users read own reward ledger"
  ON public.reward_ledger FOR SELECT TO authenticated USING (auth.uid() = user_id);
GRANT SELECT ON public.reward_ledger TO authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.reward_ledger FROM anon, authenticated;

-- Preserve existing likes by recording each eligible like once.
WITH inserted_rewards AS (
  INSERT INTO public.reward_ledger (event_key, user_id, blue_points_delta, amount_delta)
  SELECT
    'like:' || liked.post_id::text || ':' || liked.user_id::text,
    post.user_id,
    1,
    0.10
  FROM public.likes AS liked
  JOIN public.posts AS post ON post.id = liked.post_id
  WHERE post.user_id IS NOT NULL
    AND post.user_id::text <> liked.user_id::text
  ON CONFLICT (event_key) DO NOTHING
  RETURNING user_id, blue_points_delta, amount_delta
),
reward_totals AS (
  SELECT user_id, sum(blue_points_delta) AS blue_points, sum(amount_delta) AS amount
  FROM inserted_rewards
  GROUP BY user_id
)
INSERT INTO public.accounts (id, balance, blue_points)
SELECT user_id, amount, blue_points FROM reward_totals
ON CONFLICT (id) DO UPDATE
SET balance = public.accounts.balance + EXCLUDED.balance,
    blue_points = public.accounts.blue_points + EXCLUDED.blue_points;

CREATE OR REPLACE FUNCTION public.award_post_like_reward()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  post_owner uuid;
  reward_inserted boolean;
BEGIN
  SELECT user_id INTO post_owner FROM public.posts WHERE id = NEW.post_id;
  IF post_owner IS NULL OR post_owner = NEW.user_id THEN
    RETURN NEW;
  END IF;

  INSERT INTO public.reward_ledger (event_key, user_id, blue_points_delta, amount_delta)
  VALUES ('like:' || NEW.post_id::text || ':' || NEW.user_id::text, post_owner, 1, 0.10)
  ON CONFLICT (event_key) DO NOTHING
  RETURNING true INTO reward_inserted;

  IF reward_inserted THEN
    INSERT INTO public.accounts (id, balance, blue_points)
    VALUES (post_owner, 0.10, 1)
    ON CONFLICT (id) DO UPDATE
    SET balance = public.accounts.balance + 0.10,
        blue_points = public.accounts.blue_points + 1;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS award_post_like_reward ON public.likes;
CREATE TRIGGER award_post_like_reward
  AFTER INSERT ON public.likes
  FOR EACH ROW EXECUTE FUNCTION public.award_post_like_reward();

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  new_username text;
  new_referral_code text;
  referrer_id uuid;
  reward_inserted boolean;
BEGIN
  new_username := split_part(COALESCE(NEW.email, ''), '@', 1);
  new_referral_code := upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 10));

  INSERT INTO public.profiles (id, username, full_name, avatar_url, referral_code)
  VALUES (
    NEW.id,
    new_username,
    COALESCE(NULLIF(NEW.raw_user_meta_data ->> 'full_name', ''), new_username),
    COALESCE(NEW.raw_user_meta_data ->> 'avatar_url', ''),
    new_referral_code
  )
  ON CONFLICT (id) DO UPDATE
  SET referral_code = COALESCE(NULLIF(public.profiles.referral_code, ''), EXCLUDED.referral_code);

  INSERT INTO public.accounts (id, balance, blue_points)
  VALUES (NEW.id, 0, 0)
  ON CONFLICT (id) DO NOTHING;

  SELECT id INTO referrer_id
  FROM public.profiles
  WHERE referral_code = upper(trim(COALESCE(NEW.raw_user_meta_data ->> 'referral_code', '')))
    AND id <> NEW.id;

  IF referrer_id IS NOT NULL THEN
    UPDATE public.profiles SET referred_by = referrer_id WHERE id = NEW.id AND referred_by IS NULL;
    IF FOUND THEN
      INSERT INTO public.reward_ledger (event_key, user_id, blue_points_delta, amount_delta)
      VALUES
        ('referral:' || NEW.id::text || ':' || referrer_id::text, referrer_id, 100, 10.00),
        ('referral:' || NEW.id::text || ':' || NEW.id::text, NEW.id, 100, 10.00)
      ON CONFLICT (event_key) DO NOTHING;

      WITH referral_rewards AS (
        SELECT user_id, sum(blue_points_delta) AS blue_points, sum(amount_delta) AS amount
        FROM public.reward_ledger
        WHERE event_key IN (
          'referral:' || NEW.id::text || ':' || referrer_id::text,
          'referral:' || NEW.id::text || ':' || NEW.id::text
        )
        GROUP BY user_id
      )
      INSERT INTO public.accounts (id, balance, blue_points)
      SELECT user_id, amount, blue_points FROM referral_rewards
      ON CONFLICT (id) DO UPDATE
      SET balance = public.accounts.balance + EXCLUDED.balance,
          blue_points = public.accounts.blue_points + EXCLUDED.blue_points;
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

CREATE TABLE IF NOT EXISTS public.withdrawal_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL,
  upi_or_account text NOT NULL CHECK (length(trim(upi_or_account)) > 0),
  ifsc text,
  amount numeric(12, 2) NOT NULL CHECK (amount >= 100),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'rejected')),
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.withdrawal_requests ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "users read own withdrawal requests" ON public.withdrawal_requests;
CREATE POLICY "users read own withdrawal requests"
  ON public.withdrawal_requests FOR SELECT TO authenticated USING (auth.uid() = user_id);
GRANT SELECT ON public.withdrawal_requests TO authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.withdrawal_requests FROM anon, authenticated;

-- Carry forward requests created by the previous quoted payoutRequests table.
DO $$
BEGIN
  IF to_regclass('public."payoutRequests"') IS NOT NULL THEN
    EXECUTE $copy$
      INSERT INTO public.withdrawal_requests
        (user_id, name, upi_or_account, ifsc, amount, status, created_at)
      SELECT
        legacy.user_id,
        legacy.name,
        COALESCE(NULLIF(to_jsonb(legacy) ->> 'upi_or_account', ''), to_jsonb(legacy) ->> 'upi'),
        NULLIF(to_jsonb(legacy) ->> 'ifsc', ''),
        legacy.amount,
        CASE WHEN legacy.status IN ('pending', 'paid', 'rejected') THEN legacy.status ELSE 'pending' END,
        legacy.created_at
      FROM public."payoutRequests" AS legacy
      WHERE COALESCE(NULLIF(to_jsonb(legacy) ->> 'upi_or_account', ''), to_jsonb(legacy) ->> 'upi') IS NOT NULL
        AND length(trim(COALESCE(NULLIF(to_jsonb(legacy) ->> 'upi_or_account', ''), to_jsonb(legacy) ->> 'upi'))) > 0
        AND legacy.amount >= 100
        AND NOT EXISTS (
          SELECT 1
          FROM public.withdrawal_requests AS current_request
          WHERE current_request.user_id = legacy.user_id
            AND current_request.created_at = legacy.created_at
            AND current_request.amount = legacy.amount
            AND current_request.upi_or_account = COALESCE(NULLIF(to_jsonb(legacy) ->> 'upi_or_account', ''), to_jsonb(legacy) ->> 'upi')
        )
    $copy$;

    EXECUTE 'ALTER TABLE public."payoutRequests" ENABLE ROW LEVEL SECURITY';
    EXECUTE 'DROP POLICY IF EXISTS "users create own payout requests" ON public."payoutRequests"';
    EXECUTE 'REVOKE INSERT, UPDATE, DELETE ON public."payoutRequests" FROM anon, authenticated';
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.request_payout(
  p_name text,
  p_amount numeric,
  p_upi_or_account text,
  p_ifsc text DEFAULT NULL
)
RETURNS public.withdrawal_requests
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  current_user_id uuid := auth.uid();
  updated_balance numeric(12, 2);
  new_request public.withdrawal_requests;
BEGIN
  IF current_user_id IS NULL THEN
    RAISE EXCEPTION 'Sign in to request a withdrawal.';
  END IF;
  IF p_amount IS NULL OR p_amount < 100 THEN
    RAISE EXCEPTION 'Minimum withdrawal amount is ₹100.';
  END IF;
  IF p_name IS NULL OR length(trim(p_name)) = 0 OR length(p_name) > 100 THEN
    RAISE EXCEPTION 'Enter a valid account holder name.';
  END IF;
  IF p_upi_or_account IS NULL OR length(trim(p_upi_or_account)) < 3 OR length(p_upi_or_account) > 150 THEN
    RAISE EXCEPTION 'Enter a valid UPI ID or bank account.';
  END IF;
  IF p_ifsc IS NOT NULL AND p_ifsc !~* '^[A-Z]{4}0[A-Z0-9]{6}$' THEN
    RAISE EXCEPTION 'Enter a valid IFSC code.';
  END IF;

  UPDATE public.accounts
  SET balance = balance - p_amount
  WHERE id = current_user_id AND balance >= p_amount
  RETURNING balance INTO updated_balance;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Insufficient available balance.';
  END IF;

  INSERT INTO public.withdrawal_requests (user_id, name, upi_or_account, ifsc, amount)
  VALUES (current_user_id, trim(p_name), trim(p_upi_or_account), NULLIF(upper(trim(p_ifsc)), ''), p_amount)
  RETURNING * INTO new_request;
  RETURN new_request;
END;
$$;
REVOKE ALL ON FUNCTION public.request_payout(text, numeric, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.request_payout(text, numeric, text, text) TO authenticated;

CREATE OR REPLACE FUNCTION public.refund_rejected_payout()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF OLD.status = 'pending' AND NEW.status = 'rejected' THEN
    UPDATE public.accounts
    SET balance = balance + NEW.amount
    WHERE id = NEW.user_id;
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS refund_rejected_payout ON public.withdrawal_requests;
CREATE TRIGGER refund_rejected_payout
  AFTER UPDATE OF status ON public.withdrawal_requests
  FOR EACH ROW EXECUTE FUNCTION public.refund_rejected_payout();

NOTIFY pgrst, 'reload schema';
