name: Build AAB - No Data Used
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build App
        run: |
          npm ci --legacy-peer-deps
          npm run build
          npx cap sync android

      - name: Build AAB
        run: |
          cd android
          chmod +x gradlew
         ./gradlew bundleDebug --no-daemon

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: my-app-aab
          path: android/app/build/outputs/bundle/debug/*.aab